<?php

namespace App\Nova;

use App\Http\Controllers\Gitlab\UserController;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\DateTime;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class GitlabUser extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var class-string<\App\Models\GitlabUser>
     */
    public static $model = \App\Models\GitlabUser::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'username';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'email', 'username', 'person_id'
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable()->hideWhenCreating(),

            Text::make('Username')
                ->sortable()->hideWhenCreating(),
//                ->rules('required','max:255','unique:gitlab_users,username'),

            Text::make('Email')
//                ->rules('required','email','unique:gitlab_users,email')
                ->sortable()->hideWhenCreating(),

            DateTime::make('Created At')->hideWhenCreating()->hideWhenUpdating()->hideFromIndex(),

            Boolean::make('State')
            ->trueValue('active')
            ->falseValue('blocked')->hideWhenCreating(),

            Boolean::make('Is Admin')->hideFromIndex()->hideWhenCreating(),

            BelongsTo::make('Person')->showOnIndex()->sortable()->searchable()
                ->creationRules('required', 'unique:gitlab_users,person_id'),

            BelongsToMany::make('Gitlab Project', 'projects')->hideFromIndex()->searchable(),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function cards(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function lenses(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function actions(NovaRequest $request)
    {
        return [];
    }

    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey(); // TODO: Change the autogenerated stub
    }
}
